### ISSUE TITLE
Current PyplotImageViewer does not work well with InjectProcess

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/concert#327]
The delayed starting of the viewing routine introduced in 1a8d23b82b35564bcc1d36ad21fd527e8a6bfec8 blocks the main thread when combined with [InjectProcess](https://github.com/ufo-kit/concert/blob/master/concert/ext/ufo.py#L30).

**Comment by MariaMatveeva** [comment]
I get an error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/concert-0.11.0.dev0-py2.7.egg/EGG-INFO/scripts/concert", line 406, in run
    module = cs.load(session) if session else None
  File "/usr/lib/python2.7/site-packages/concert-0.11.0.dev0-py2.7.egg/concert/session/management.py", line 106, in load
    return imp.load_source(session, path(session))
  File "/home/maria/.local/share/concert/327.py", line 29, in <module>
    inject(generator(5), InjectProcess(viewer()))
  File "/usr/lib/python2.7/site-packages/concert-0.11.0.dev0-py2.7.egg/concert/ext/ufo.py", line 67, in __init__
    raise ValueError(msg)
ValueError: graph is neither Ufo.TaskGraph nor Ufo.TaskNode
```

**Comment by tfarago** [comment]
Can you provide the code excerpt which causes this error?

**Comment by MariaMatveeva** [comment]
```
def generator(n):
    for i in range(n):
        yield np.ones((256, 256)) * i

viewer = PyplotImageViewer()
inject(generator(5), InjectProcess(viewer()))
```

**Comment by tfarago** [comment]
`InjectProcess` is meant to create UFO graphs and the parameter should be an UFO task or a graph, not a coroutine. Your code will work when you do `inject(generator(5), viewer())`.
