### ISSUE TITLE
Poblem with instance names in logging

### ISSUE THREAD

**Issue by MarcusZuber** [ufo-kit/concert#453]
In some configurations the logging with device instance names creates an exception in this line:
https://github.com/ufo-kit/concert/blob/050185443ade7c45c94c71ab67983e0d5a1e972a/concert/base.py#L59

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/concert-0.11.0.dev0-py2.7.egg/concert/base.py", line 539, in __set__
    super(Quantity, self).__set__(instance, converted)
  File "/usr/local/lib/python2.7/dist-packages/concert-0.11.0.dev0-py2.7.egg/concert/base.py", line 360, in __set__
    instance_name = _find_object_by_name(instance)
  File "/usr/local/lib/python2.7/dist-packages/concert-0.11.0.dev0-py2.7.egg/concert/base.py", line 72, in _find_object_by_name
    instance_name = _find_in_dict(frames[i][0].f_locals)
  File "/usr/local/lib/python2.7/dist-packages/concert-0.11.0.dev0-py2.7.egg/concert/base.py", line 59, in _find_in_dict
    if obj == instance:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

I guess, that this can happen, if one device is existing multiple times in the same stack level.

**Comment by tfarago** [comment]
Nope, that's when you have a numpy array in the session.
